server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    name: security_demo
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/security_demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: admin
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.oyr.admin

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


# 自定义cas的一些属性配置
security:
  cas:
    server: # cas server 的配置
      host: https://server.cas.com:8443/cas
      login: /login
      logout: /logout?service=http://client1.cas.com:8081 # logout后面加上当前service的地址，为了logout后可以跳转回当前service
    service: # cas client 配置
      host: http://client1.cas.com:8081 # 应用的host
      login: /login  # 应用登录的地址
      logout: /logout   # 应用登出的地址
